/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

/**
 *
 * @author ivann
 */
public class CompraExitosa extends javax.swing.JFrame {

    /**
     * Creates new form CompraExitosa
     */
    public CompraExitosa() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGPanel1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        tittleLabel3 = new javax.swing.JLabel();
        imagenLabel = new javax.swing.JLabel();
        mensaje1Label = new javax.swing.JLabel();
        mensaje2Label = new javax.swing.JLabel();
        volverButton = new javax.swing.JButton();
        salirButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bGPanel1.setBackground(new java.awt.Color(255, 255, 255));
        bGPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        tittleLabel3.setFont(new java.awt.Font("Candara", 0, 36)); // NOI18N
        tittleLabel3.setForeground(new java.awt.Color(255, 255, 255));
        tittleLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tittleLabel3.setText("Conservas Dorita");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addComponent(tittleLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(tittleLabel3)
                .addGap(15, 15, 15))
        );

        bGPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 80));

        imagenLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDorita/Check.png"))); // NOI18N
        bGPanel1.add(imagenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 230, 220));

        mensaje1Label.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        mensaje1Label.setText("¡Felicidades su pago ha sido realizado con exito!");
        bGPanel1.add(mensaje1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 600, 30));

        mensaje2Label.setFont(new java.awt.Font("Yu Gothic", 2, 18)); // NOI18N
        mensaje2Label.setText("Gracias por su compra");
        bGPanel1.add(mensaje2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 200, -1));

        volverButton.setBackground(new java.awt.Color(0, 102, 255));
        volverButton.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        volverButton.setText("Volver al Menu Principal");
        volverButton.setBorder(null);
        volverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButtonActionPerformed(evt);
            }
        });
        bGPanel1.add(volverButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 170, 30));

        salirButton.setBackground(new java.awt.Color(0, 102, 255));
        salirButton.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        salirButton.setText("Salir");
        salirButton.setBorder(null);
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });
        bGPanel1.add(salirButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 140, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bGPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bGPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButtonActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_volverButtonActionPerformed

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_salirButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompraExitosa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompraExitosa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompraExitosa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompraExitosa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompraExitosa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bGPanel1;
    private javax.swing.JLabel imagenLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mensaje1Label;
    private javax.swing.JLabel mensaje2Label;
    private javax.swing.JButton salirButton;
    private javax.swing.JLabel tittleLabel3;
    private javax.swing.JButton volverButton;
    // End of variables declaration//GEN-END:variables
}
