/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Joaquin
 */
public class Credito extends javax.swing.JFrame {

    /**
     * Creates new form Credito
     */
    public Credito() {
        initComponents();
        setUp();
            addFocusListeners();
            setLocationRelativeTo(null);
    }
     
    
    private void addFocusListeners() {
        addFocusListenerToField(titularCréditoText, "Nombre del titular");
        addFocusListenerToField(tarjetaCréditoText, "Número de tarjeta");
        addFocusListenerToField(fechaText, "Fecha de vencimiento");
        addFocusListenerToField(cvcText, "CVC / CVV");
    }

    private void addFocusListenerToField(javax.swing.JTextField field, String defaultText) {
        field.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (field.getText().equals(defaultText) && field.getForeground() == Color.GRAY) {
                    field.setText("");
                    field.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (field.getText().isEmpty()) {
                    field.setText(defaultText);
                    field.setForeground(Color.GRAY);
                }
            }
        });
    }

    
    private void setUp () {
        inicializarCampo(titularCréditoText, "Nombre del titular");
        inicializarCampo(tarjetaCréditoText, "Número de tarjeta"); 
        inicializarCampo(cvcText, "CVC / CVV");
        inicializarCampo(fechaText, "Fecha de vencimiento");
    }
        
    private void inicializarCampo(javax.swing.JTextField campo, String textoPredeterminado) {
   
        if(campo.getText().isEmpty())
        {
            campo.setText(textoPredeterminado);
            campo.setForeground(Color.GRAY);
        }
    }
    
    private boolean validarNombre() {
        String nombre = titularCréditoText.getText().trim();
        if (!nombre.matches("^[A-Z][a-zA-Z]*(\\s[A-Z][a-zA-Z]*)*$")) {
            JOptionPane.showMessageDialog(this, "El nombre del titular debe contener solo letras y cada palabra debe empezar con mayúscula.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    
    private boolean validarNumeroTarjeta() {
        String numeroTarjeta = tarjetaCréditoText.getText().trim();
        if (!numeroTarjeta.matches("\\d{16}")) {
            JOptionPane.showMessageDialog(this, "El número de tarjeta debe contener exactamente 16 dígitos.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private boolean validarCVC() {
        String cvc = cvcText.getText().trim();
        if (!cvc.matches("\\d{4}")) {
            JOptionPane.showMessageDialog(this, "El CVC debe contener exactamente 3 dígitos.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private boolean validarFecha() {
    String fecha = fechaText.getText().trim();
    if (!fecha.matches("\\d{2}/\\d{2}")) {
        JOptionPane.showMessageDialog(this, "La fecha debe contener el formato MM/YY.", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    String[] partesFecha = fecha.split("/");
    try {
        int mes = Integer.parseInt(partesFecha[0]);
        int año = Integer.parseInt(partesFecha[1]);

        if (mes < 1 || mes > 12 || año > 23) {
            JOptionPane.showMessageDialog(this, "Fecha de vencimiento inválida.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    } catch (NumberFormatException | ArrayIndexOutOfBoundsException e) {
        JOptionPane.showMessageDialog(this, "La fecha debe contener el formato MM/YY.", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    return true;
} 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tittleLabel3 = new javax.swing.JLabel();
        tittuloLabel = new javax.swing.JLabel();
        elegirComboBox1 = new javax.swing.JComboBox<>();
        completarLabel1 = new javax.swing.JLabel();
        titularCréditoText = new javax.swing.JTextField();
        tarjetaCréditoText = new javax.swing.JTextField();
        fechaText = new javax.swing.JTextField();
        cvcText = new javax.swing.JTextField();
        continuarButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        tittleLabel3.setFont(new java.awt.Font("Candara", 0, 36)); // NOI18N
        tittleLabel3.setForeground(new java.awt.Color(255, 255, 255));
        tittleLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tittleLabel3.setText("Conservas Dorita");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(tittleLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(tittleLabel3)
                .addGap(15, 15, 15))
        );

        tittuloLabel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        tittuloLabel.setText("TARJETA DE CRÉDITO");

        elegirComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "                                         Visa", "                                    MasterCard" }));
        elegirComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elegirComboBox1ActionPerformed(evt);
            }
        });

        completarLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 3, 14)); // NOI18N
        completarLabel1.setText("Completa la información");

        titularCréditoText.setForeground(new java.awt.Color(204, 204, 204));
        titularCréditoText.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        titularCréditoText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titularCréditoTextMousePressed(evt);
            }
        });

        tarjetaCréditoText.setForeground(new java.awt.Color(204, 204, 204));
        tarjetaCréditoText.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tarjetaCréditoText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tarjetaCréditoTextMousePressed(evt);
            }
        });
        tarjetaCréditoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarjetaCréditoTextActionPerformed(evt);
            }
        });

        fechaText.setForeground(new java.awt.Color(204, 204, 204));
        fechaText.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        fechaText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fechaTextMousePressed(evt);
            }
        });
        fechaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaTextActionPerformed(evt);
            }
        });

        cvcText.setForeground(new java.awt.Color(204, 204, 204));
        cvcText.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        cvcText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cvcTextMousePressed(evt);
            }
        });
        cvcText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvcTextActionPerformed(evt);
            }
        });

        continuarButton1.setBackground(new java.awt.Color(51, 153, 255));
        continuarButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        continuarButton1.setText("Continuar");
        continuarButton1.setBorder(null);
        continuarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarButton1ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDorita/VisayMastercard-.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(tittuloLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(elegirComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(continuarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(completarLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titularCréditoText, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tarjetaCréditoText, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fechaText, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(cvcText, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(tittuloLabel)
                .addGap(40, 40, 40)
                .addComponent(elegirComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(completarLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(titularCréditoText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(tarjetaCréditoText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechaText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cvcText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2)))
                .addGap(30, 30, 30)
                .addComponent(continuarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void elegirComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elegirComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elegirComboBox1ActionPerformed

    private void titularCréditoTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titularCréditoTextMousePressed

        if (titularCréditoText.getText().equals("Nombre del titular")) {
            titularCréditoText.setText("");
            titularCréditoText.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_titularCréditoTextMousePressed

    private void tarjetaCréditoTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tarjetaCréditoTextMousePressed
        if (tarjetaCréditoText.getText().equals("Número de tarjeta")){
            tarjetaCréditoText.setText("");
            tarjetaCréditoText.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tarjetaCréditoTextMousePressed

    private void tarjetaCréditoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarjetaCréditoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarjetaCréditoTextActionPerformed

    private void fechaTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechaTextMousePressed
        if (fechaText.getText().equals("Fecha de vencimiento")) {
            fechaText.setText("");
            fechaText.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_fechaTextMousePressed

    private void fechaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaTextActionPerformed

    private void cvcTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cvcTextMousePressed
        if(cvcText.getText().equals("CVC / CVV")) {
            cvcText.setText("");
            cvcText.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_cvcTextMousePressed

    private void cvcTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvcTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvcTextActionPerformed

    private void continuarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarButton1ActionPerformed
        // TODO add your handling code here:
        if (validarNombre() && validarNumeroTarjeta() && validarCVC() && validarFecha()) {

            CompraExitosa compra1 = new CompraExitosa();
            compra1.setVisible(true);
            compra1.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_continuarButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Credito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Credito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Credito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Credito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Credito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel completarLabel1;
    private javax.swing.JButton continuarButton1;
    private javax.swing.JTextField cvcText;
    private javax.swing.JComboBox<String> elegirComboBox1;
    private javax.swing.JTextField fechaText;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tarjetaCréditoText;
    private javax.swing.JLabel tittleLabel3;
    private javax.swing.JLabel tittuloLabel;
    private javax.swing.JTextField titularCréditoText;
    // End of variables declaration//GEN-END:variables
}
