/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.JOptionPane;


/**
 *
 * @author ivann
 */
public class Débito extends javax.swing.JFrame {

    /**
     * Creates new form Débito
     */
    public Débito() {
        
                initComponents();
                setUp();
                addFocusListeners();
                setLocationRelativeTo(null);
        
    }
    
    private void addFocusListeners() {
        addFocusListenerToField(titularDebText, "Nombre del titular");
        addFocusListenerToField(tarjetaDebText, "Número de tarjeta");
        addFocusListenerToField(fechaText, "Fecha de vencimiento");
        addFocusListenerToField(cvcText, "CVC / CVV");
    }

    private void addFocusListenerToField(javax.swing.JTextField field, String defaultText) {
        field.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (field.getText().equals(defaultText) && field.getForeground() == Color.GRAY) {
                    field.setText("");
                    field.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (field.getText().isEmpty()) {
                    field.setText(defaultText);
                    field.setForeground(Color.GRAY);
                }
            }
        });
    }

    
    private void setUp () {
        inicializarCampo(titularDebText, "Nombre del titular");
        inicializarCampo(tarjetaDebText, "Número de tarjeta"); 
        inicializarCampo(cvcText, "CVC / CVV");
        inicializarCampo(fechaText, "Fecha de vencimiento");
    }
        
    private void inicializarCampo(javax.swing.JTextField campo, String textoPredeterminado) {
   
        if(campo.getText().isEmpty())
        {
            campo.setText(textoPredeterminado);
            campo.setForeground(Color.GRAY);
        }
    }
    
    private boolean validarNombre() {
        String nombre = titularDebText.getText().trim();
        if (!nombre.matches("^[A-Z][a-zA-Z]*(\\s[A-Z][a-zA-Z]*)*$")) {
            JOptionPane.showMessageDialog(this, "El nombre del titular debe contener solo letras y cada palabra debe empezar con mayúscula.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    
    private boolean validarNumeroTarjeta() {
        String numeroTarjeta = tarjetaDebText.getText().trim();
        if (!numeroTarjeta.matches("\\d{16}")) {
            JOptionPane.showMessageDialog(this, "El número de tarjeta debe contener exactamente 16 dígitos.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private boolean validarCVC() {
        String cvc = cvcText.getText().trim();
        if (!cvc.matches("\\d{3}")) {
            JOptionPane.showMessageDialog(this, "El CVC debe contener exactamente 3 dígitos.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private boolean validarFecha() {
    String fecha = fechaText.getText().trim();
    if (!fecha.matches("\\d{2}/\\d{2}")) {
        JOptionPane.showMessageDialog(this, "La fecha debe contener el formato MM/YY.", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    String[] partesFecha = fecha.split("/");
    try {
        int mes = Integer.parseInt(partesFecha[0]);
        int año = Integer.parseInt(partesFecha[1]);

        if (mes < 1 || mes > 12 || año > 23) {
            JOptionPane.showMessageDialog(this, "Fecha de vencimiento inválida.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    } catch (NumberFormatException | ArrayIndexOutOfBoundsException e) {
        JOptionPane.showMessageDialog(this, "La fecha debe contener el formato MM/YY.", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    return true;
}    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGPanel1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        tittleLabel3 = new javax.swing.JLabel();
        tittuloLabel = new javax.swing.JLabel();
        elegirComboBox1 = new javax.swing.JComboBox<>();
        completarLabel1 = new javax.swing.JLabel();
        titularDebText = new javax.swing.JTextField();
        tarjetaDebText = new javax.swing.JTextField();
        fechaText = new javax.swing.JTextField();
        cvcText = new javax.swing.JTextField();
        continuarButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bGPanel1.setBackground(new java.awt.Color(255, 255, 255));
        bGPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        tittleLabel3.setFont(new java.awt.Font("Candara", 0, 36)); // NOI18N
        tittleLabel3.setForeground(new java.awt.Color(255, 255, 255));
        tittleLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tittleLabel3.setText("Conservas Dorita");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(tittleLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(tittleLabel3)
                .addGap(15, 15, 15))
        );

        bGPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 80));

        tittuloLabel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        tittuloLabel.setText("TARJETA DE DÉBITO");
        bGPanel1.add(tittuloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        elegirComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "                                         Visa", "                                    MasterCard" }));
        elegirComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elegirComboBox1ActionPerformed(evt);
            }
        });
        bGPanel1.add(elegirComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 310, 30));

        completarLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 3, 14)); // NOI18N
        completarLabel1.setText("Completa la información");
        bGPanel1.add(completarLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 180, 20));

        titularDebText.setForeground(new java.awt.Color(204, 204, 204));
        titularDebText.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        titularDebText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titularDebTextMousePressed(evt);
            }
        });
        bGPanel1.add(titularDebText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 310, 40));

        tarjetaDebText.setForeground(new java.awt.Color(204, 204, 204));
        tarjetaDebText.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tarjetaDebText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tarjetaDebTextMousePressed(evt);
            }
        });
        tarjetaDebText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarjetaDebTextActionPerformed(evt);
            }
        });
        bGPanel1.add(tarjetaDebText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 310, 40));

        fechaText.setForeground(new java.awt.Color(204, 204, 204));
        fechaText.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        fechaText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fechaTextMousePressed(evt);
            }
        });
        fechaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaTextActionPerformed(evt);
            }
        });
        bGPanel1.add(fechaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 140, 40));

        cvcText.setForeground(new java.awt.Color(204, 204, 204));
        cvcText.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        cvcText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cvcTextMousePressed(evt);
            }
        });
        cvcText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvcTextActionPerformed(evt);
            }
        });
        bGPanel1.add(cvcText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 140, 40));

        continuarButton1.setBackground(new java.awt.Color(51, 153, 255));
        continuarButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        continuarButton1.setText("Continuar");
        continuarButton1.setBorder(null);
        continuarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarButton1ActionPerformed(evt);
            }
        });
        bGPanel1.add(continuarButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 180, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDorita/VisayMastercard-.png"))); // NOI18N
        bGPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 290, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bGPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bGPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void elegirComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elegirComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elegirComboBox1ActionPerformed

    private void titularDebTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titularDebTextMousePressed

        if (titularDebText.getText().equals("Nombre del titular")) {
            titularDebText.setText("");
            titularDebText.setForeground(Color.BLACK);
        }
        
    }//GEN-LAST:event_titularDebTextMousePressed

    private void tarjetaDebTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tarjetaDebTextMousePressed
        
        if (tarjetaDebText.getText().equals("Número de tarjeta")){
            tarjetaDebText.setText("");
            tarjetaDebText.setForeground(Color.BLACK);
        }  
    }//GEN-LAST:event_tarjetaDebTextMousePressed

    private void tarjetaDebTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarjetaDebTextActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tarjetaDebTextActionPerformed

    private void fechaTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechaTextMousePressed
        
        if (fechaText.getText().equals("Fecha de vencimiento")) {
            fechaText.setText("");
            fechaText.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_fechaTextMousePressed

    private void fechaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaTextActionPerformed

    private void cvcTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cvcTextMousePressed
      
        if(cvcText.getText().equals("CVC / CVV")) {
            cvcText.setText("");
            cvcText.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_cvcTextMousePressed

    private void cvcTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvcTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvcTextActionPerformed

    private void continuarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarButton1ActionPerformed
        // TODO add your handling code here:
        if (validarNombre() && validarNumeroTarjeta() && validarCVC() && validarFecha()) {

            CompraExitosa compra1 = new CompraExitosa();
            compra1.setVisible(true);
            compra1.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_continuarButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Débito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Débito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Débito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Débito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Débito().setVisible(true);
            }
        });
    }

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bGPanel1;
    private javax.swing.JLabel completarLabel1;
    private javax.swing.JButton continuarButton1;
    private javax.swing.JTextField cvcText;
    private javax.swing.JComboBox<String> elegirComboBox1;
    private javax.swing.JTextField fechaText;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tarjetaDebText;
    private javax.swing.JLabel tittleLabel3;
    private javax.swing.JLabel tittuloLabel;
    private javax.swing.JTextField titularDebText;
    // End of variables declaration//GEN-END:variables
}
