/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

/**
 *
 * @author ivann
 */
public class MetodoDePago extends javax.swing.JFrame {

    /**
     * Creates new form MetodoDePago
     */
    public MetodoDePago() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGPanel1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        tittleLabel3 = new javax.swing.JLabel();
        escogeLabel1 = new javax.swing.JLabel();
        débitoButton2 = new javax.swing.JButton();
        créditoButton3 = new javax.swing.JButton();
        yapeButton4 = new javax.swing.JButton();
        plinButton1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bGPanel1.setBackground(new java.awt.Color(255, 255, 255));
        bGPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        tittleLabel3.setFont(new java.awt.Font("Candara", 0, 36)); // NOI18N
        tittleLabel3.setForeground(new java.awt.Color(255, 255, 255));
        tittleLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tittleLabel3.setText("Conservas Dorita");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(179, Short.MAX_VALUE)
                .addComponent(tittleLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(tittleLabel3)
                .addGap(15, 15, 15))
        );

        bGPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 80));

        escogeLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 3, 14)); // NOI18N
        escogeLabel1.setText("Escoge tu medio de pago");
        bGPanel1.add(escogeLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 180, -1));

        débitoButton2.setBackground(new java.awt.Color(51, 153, 255));
        débitoButton2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        débitoButton2.setText("TARJETA DE DÉBITO");
        débitoButton2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        débitoButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        débitoButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                débitoButton2ActionPerformed(evt);
            }
        });
        bGPanel1.add(débitoButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 400, 40));

        créditoButton3.setBackground(new java.awt.Color(51, 153, 255));
        créditoButton3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        créditoButton3.setText("TARJETA DE CRÉDITO");
        créditoButton3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        créditoButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        créditoButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                créditoButton3ActionPerformed(evt);
            }
        });
        bGPanel1.add(créditoButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 400, 40));

        yapeButton4.setBackground(new java.awt.Color(51, 153, 255));
        yapeButton4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        yapeButton4.setText("YAPE");
        yapeButton4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        yapeButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        yapeButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yapeButton4ActionPerformed(evt);
            }
        });
        bGPanel1.add(yapeButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 400, 40));

        plinButton1.setBackground(new java.awt.Color(51, 153, 255));
        plinButton1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        plinButton1.setText("PLIN");
        plinButton1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plinButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plinButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plinButton1ActionPerformed(evt);
            }
        });
        bGPanel1.add(plinButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 400, 40));

        jButton1.setBackground(new java.awt.Color(102, 204, 255));
        jButton1.setText("Volver al Menú Principal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        bGPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 170, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bGPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bGPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void débitoButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_débitoButton2ActionPerformed
        // TODO add your handling code here:
        Débito debito = new Débito();
        debito.setVisible(true);
        debito.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_débitoButton2ActionPerformed

    private void créditoButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_créditoButton3ActionPerformed
        // TODO add your handling code here:
        Credito credito = new Credito();
        credito.setVisible(true);
        credito.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_créditoButton3ActionPerformed

    private void yapeButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yapeButton4ActionPerformed
        // TODO add your handling code here:
        Yape yape = new Yape();
        yape.setVisible(true);
        yape.setLocationRelativeTo(null);
        this.dispose(); 
    }//GEN-LAST:event_yapeButton4ActionPerformed

    private void plinButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plinButton1ActionPerformed
        // TODO add your handling code here:
       Plin plin = new Plin();
        plin.setVisible(true);
        plin.setLocationRelativeTo(null);
        this.dispose(); 
    }//GEN-LAST:event_plinButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu newframe = new Menu();
        newframe.setVisible(true);
        newframe.setLocationRelativeTo(null);
        this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MetodoDePago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MetodoDePago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MetodoDePago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MetodoDePago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MetodoDePago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bGPanel1;
    private javax.swing.JButton créditoButton3;
    private javax.swing.JButton débitoButton2;
    private javax.swing.JLabel escogeLabel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton plinButton1;
    private javax.swing.JLabel tittleLabel3;
    private javax.swing.JButton yapeButton4;
    // End of variables declaration//GEN-END:variables
}
