/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Joaquin
 */
public class Plin extends javax.swing.JFrame {

    /**
     * Creates new form Plin
     */
    public Plin() {
        initComponents();
        setUp();
        addFocusListeners();
        setLocationRelativeTo(null);
    }
    
    private void addFocusListeners() {
        addFocusListenerToField(nombre_textfield, "Nombre del titular");
        addFocusListenerToField(apellido_textfield, "Apellido del titular");
        addFocusListenerToField(email_textfield, "email del titular");
        addFocusListenerToField(dni_textfield, "DNI del titular");
    }
    
    private void addFocusListenerToField(javax.swing.JTextField field, String defaultText) {
        field.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (field.getText().equals(defaultText) && field.getForeground() == Color.GRAY) {
                    field.setText("");
                    field.setForeground(Color.BLACK);
                }
            }
            
        @Override
            public void focusLost(FocusEvent e) {
                if (field.getText().isEmpty()) {
                    field.setText(defaultText);
                    field.setForeground(Color.GRAY);
                }
            }
        });
    }
    
    private void setUp() {
        inicializarCampo(nombre_textfield, "Nombre del titular");
        inicializarCampo(apellido_textfield, "Apellido del titular");
        inicializarCampo(email_textfield, "email del titular");
        inicializarCampo(dni_textfield, "DNI del titular");
    }

    private void inicializarCampo(javax.swing.JTextField campo, String textoPredeterminado) {
        if (campo.getText().isEmpty()) {
            campo.setText(textoPredeterminado);
            campo.setForeground(Color.GRAY);
        }
    }

        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        nombre_textfield = new javax.swing.JTextField();
        apellido_textfield = new javax.swing.JTextField();
        email_textfield = new javax.swing.JTextField();
        dni_textfield = new javax.swing.JTextField();
        mensajerror = new javax.swing.JLabel();
        continuar_button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tittleLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Completa la información");

        nombre_textfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombre_textfieldMousePressed(evt);
            }
        });
        nombre_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_textfieldActionPerformed(evt);
            }
        });

        apellido_textfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                apellido_textfieldMousePressed(evt);
            }
        });
        apellido_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellido_textfieldActionPerformed(evt);
            }
        });

        email_textfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                email_textfieldMousePressed(evt);
            }
        });

        dni_textfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dni_textfieldMousePressed(evt);
            }
        });
        dni_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dni_textfieldActionPerformed(evt);
            }
        });

        continuar_button.setText("CONTINUAR");
        continuar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuar_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel4))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apellido_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dni_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 30, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(mensajerror))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(continuar_button)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(nombre_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(apellido_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(email_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dni_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(continuar_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(mensajerror)
                .addGap(27, 27, 27))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 270, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Light", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PLIN");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, -1));

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 74, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDorita/QRFALSO2.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 220, 220));

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));

        tittleLabel3.setFont(new java.awt.Font("Candara", 0, 36)); // NOI18N
        tittleLabel3.setForeground(new java.awt.Color(255, 255, 255));
        tittleLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tittleLabel3.setText("Conservas Dorita");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(tittleLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(tittleLabel3)
                .addGap(15, 15, 15))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombre_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_textfieldActionPerformed

    }//GEN-LAST:event_nombre_textfieldActionPerformed

    private void apellido_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellido_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellido_textfieldActionPerformed

    private void dni_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dni_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dni_textfieldActionPerformed

    private void continuar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuar_buttonActionPerformed
        String nombre = nombre_textfield.getText();
        String apellido = apellido_textfield.getText();
        String emailText = email_textfield.getText();

        //EMAIL
        String email = null;
        for (char caracter : emailText.toCharArray()) {
            if (!Character.isDigit(caracter)) {
                JOptionPane.showMessageDialog(null, "El texto ingresado no es un email correcto");
                break; // No es necesario seguir verificando si ya encontramos un carácter no numérico
            }else {
                email = emailText;
            }

            //Solamente aplica para DNI
            String DNI = null;
            String dniText = dni_textfield.getText();

            for (char character : dniText.toCharArray()) {
                if (!Character.isDigit(caracter)) {
                    JOptionPane.showMessageDialog(null, "El texto ingresado no es un número correcto");
                    break; // No es necesario seguir verificando si ya encontramos un carácter no numérico
                }else {
                    DNI = dniText;
                }
            }
            if (!nombre.isEmpty() && !apellido.isEmpty() && !email.isEmpty() && !dniText.isEmpty()){
                CompraExitosa a = new CompraExitosa();
                a.setVisible(true);
                this.setVisible(false);
            }else if (nombre.isEmpty() || apellido.isEmpty() || email.isEmpty() || dniText.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Se debe completar todos los campos");

            } else {
                JOptionPane.showMessageDialog(null, "Se debe completar todos los campos");
            }
        }
    }//GEN-LAST:event_continuar_buttonActionPerformed

    private void nombre_textfieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombre_textfieldMousePressed
        if (nombre_textfield.getText().equals("Nombre del titular")) {
            nombre_textfield.setText("");
            nombre_textfield.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_nombre_textfieldMousePressed

    private void apellido_textfieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apellido_textfieldMousePressed
        if (apellido_textfield.getText().equals("Apellido del titular")){
            apellido_textfield.setText("");
            apellido_textfield.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_apellido_textfieldMousePressed

    private void dni_textfieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dni_textfieldMousePressed
        if(dni_textfield.getText().equals("DNI del titular")) {
            dni_textfield.setText("");
            dni_textfield.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_dni_textfieldMousePressed

    private void email_textfieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_email_textfieldMousePressed
        if (email_textfield.getText().equals("email del titular")) {
            email_textfield.setText("");
            email_textfield.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_email_textfieldMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Plin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Plin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Plin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Plin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Plin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido_textfield;
    private javax.swing.JButton continuar_button;
    private javax.swing.JTextField dni_textfield;
    private javax.swing.JTextField email_textfield;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel mensajerror;
    private javax.swing.JTextField nombre_textfield;
    private javax.swing.JLabel tittleLabel3;
    // End of variables declaration//GEN-END:variables
}
